spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-hml.grupomultiplica.com.br/auth/realms/multiplicacapital
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: mc-credito-cadastro-ms
      principle-attribute: preferred_username